# Generated by Django 5.1.7 on 2025-03-16 14:02

import face_detector.models
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("face_detector", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedimage",
            name="image",
            field=models.ImageField(
                upload_to=functools.partial(face_detector.models.unique_path, *("uploads",), **{})
            ),
        ),
        migrations.AlterField(
            model_name="uploadedimage",
            name="image_with_marked_faces",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=functools.partial(
                    face_detector.models.unique_path, *("processed",), **{}
                ),
            ),
        ),
    ]
